language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: BJhpYBiFjcxoCqo1+bTnxDbVxAgRI6ToOjbs3PbHKy06gX+saWA02s35G7TsaWr806WGQTf3HkqfR1jG/NW2Dl/gI3VGKv49SgxSjsmDJa+yxilNgTz5DIYedS4FCdrSkYpHP3s7OtIuVh2mylDwcmnPDwuDgNhVGTY0MM3453YTgp9jjFtiLurbT5Xc9Gme2Js3GvrtJuLg+C4KLPluxaQ1SHxZIG9SDSV0jrxTU9rrou7zFM7Q94grJtmwm8X2ZGamRDSxT6jVwKni4+QoUJ0JgW++f/iqcSU13ZkCXd95bj9s9/c+rJumBsDSemp8xUgFQ1D++CqCgCKVVQJjWpZBrTM4CV6GhOYf5BTSfLKjv8xRZlRzOztrp/PIqPTQ1z8hpgvqqnFsmBkiDIPSR4acPt1/hTBGYp7I0mAAplN9CpuKC+J7e1HEg9Vq49vBXK8dJAA+mJf6JNcRqcmfzcuygd4sBhW6b7FD3mxiQdMNW+kVNRoiQ+s71MP78RGgVLR1gHG9xI7yjSsKgGTUBkvgGziUsUB477E97s/RhLjY/Ht3EpZqJ8kyA78EMePCzGBl82eN2pIKEN6gBTMFlCu0648fFDAimqs+AvtkI/yy4dgkugjEto0vo3uwHxJtBcJCn4L84Yj15xzVoyCKPAr8hv9m4hGW3wjK/coi+Ds=
  app: gentle-everglades-89884
